# Guided Capstone Step 4. Pre-Processing and Training Data Development

**The Data Science Method**  


1.   Problem Identification 


2.   Data Wrangling 
  
 
3.   Exploratory Data Analysis   

4.   **Pre-processing and Training Data Development**  
 * Create dummy or indicator features for categorical variables
  * Standardize the magnitude of numeric features
  * Split into testing and training datasets
  * Apply scaler to the testing set
5.   Modeling 
  * Fit Models with Training Data Set
  * Review Model Outcomes â€” Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

**<font color='teal'> Start by loading the necessary packages as we did in step 3 and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [81]:
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

path = "C:\\Users\\tommc\\OneDrive\\Documents\\GitHub\\Capstone1\\Data"
os.chdir(path)
os.getcwd()

'C:\\Users\\tommc\\OneDrive\\Documents\\GitHub\\Capstone1\\Data'

**<font color='teal'>  Load the csv file you created in step 3, remember it should be saved inside your data subfolder and print the first five rows.</font>**

In [82]:
df = pd.read_csv('step3_output.csv')
df.head()

,Name,state,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Alyeska Resort,Alaska,3939,2500,1,0.0,0,2,2,0,0,2,7,76.0,2.0,1.0,1610.0,113.0,150.0,60.0,669.0,65.0,85.0,150.0,550.0,0
1,Eaglecrest Ski Area,Alaska,2600,1540,0,0.0,0,0,0,0,4,0,4,36.0,1.0,2.0,640.0,60.0,45.0,44.0,350.0,47.0,53.0,90.0,0.0,0
2,Hilltop Ski Area,Alaska,2090,294,0,0.0,0,0,0,1,0,2,3,13.0,1.0,1.0,30.0,30.0,150.0,36.0,69.0,30.0,34.0,152.0,30.0,0
3,Arizona Snowbowl,Arizona,11500,2300,0,0.0,1,0,2,2,1,2,8,55.0,4.0,2.0,777.0,104.0,122.0,81.0,260.0,89.0,89.0,122.0,0.0,1
4,Sunrise Park Resort,Arizona,11100,1800,0,0.0,0,1,2,3,1,0,7,65.0,2.0,1.2,800.0,80.0,115.0,49.0,250.0,74.0,78.0,104.0,80.0,1

In [57]:
df.dtypes

Name                  object
state                 object
summit_elev            int64
vertical_drop          int64
trams                  int64
fastEight            float64
fastSixes              int64
fastQuads              int64
quad                   int64
triple                 int64
double                 int64
surface                int64
total_chairs           int64
Runs                 float64
TerrainParks         float64
LongestRun_mi        float64
SkiableTerrain_ac    float64
Snow Making_ac       float64
daysOpenLastYear     float64
yearsOpen            float64
averageSnowfall      float64
AdultWeekday         float64
AdultWeekend         float64
projectedDaysOpen    float64
NightSkiing_ac       float64
clusters               int64
dtype: object

## Create dummy features for categorical variables

**<font color='teal'> Create dummy variables for `state`. Add the dummies back to the dataframe and remove the original column for `state`. </font>**

Hint: you can see an example of how to execute this in Aiden's article on preprocessing [here](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-pre-processing-and-training-data-development-fd2d75182967).

In [83]:
dummy = pd.get_dummies(df['state'])

In [84]:
df['state']

0       Alaska
1       Alaska
2       Alaska
3      Arizona
4      Arizona
        ...
325    Wyoming
326    Wyoming
327    Wyoming
328    Wyoming
329    Wyoming
Name: state, Length: 330, dtype: object

In [85]:
df2 = pd.concat([df.drop('state',axis=1), dummy],axis=1)

In [86]:
df2.head()

,Name,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters,Alaska,Arizona,California,Colorado,Connecticut,Idaho,Illinois,Indiana,Iowa,Maine,Maryland,Massachusetts,Michigan,Minnesota,Missouri,Montana,Nevada,New Hampshire,New Jersey,New Mexico,New York,North Carolina,Ohio,Oregon,Pennsylvania,Rhode Island,South Dakota,Tennessee,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Alyeska Resort,3939,2500,1,0.0,0,2,2,0,0,2,7,76.0,2.0,1.0,1610.0,113.0,150.0,60.0,669.0,65.0,85.0,150.0,550.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Eaglecrest Ski Area,2600,1540,0,0.0,0,0,0,0,4,0,4,36.0,1.0,2.0,640.0,60.0,45.0,44.0,350.0,47.0,53.0,90.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Hilltop Ski Area,2090,294,0,0.0,0,0,0,1,0,2,3,13.0,1.0,1.0,30.0,30.0,150.0,36.0,69.0,30.0,34.0,152.0,30.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Arizona Snowbowl,11500,2300,0,0.0,1,0,2,2,1,2,8,55.0,4.0,2.0,777.0,104.0,122.0,81.0,260.0,89.0,89.0,122.0,0.0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Sunrise Park Resort,11100,1800,0,0.0,0,1,2,3,1,0,7,65.0,2.0,1.2,800.0,80.0,115.0,49.0,250.0,74.0,78.0,104.0,80.0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [87]:
df['state']

0       Alaska
1       Alaska
2       Alaska
3      Arizona
4      Arizona
        ...
325    Wyoming
326    Wyoming
327    Wyoming
328    Wyoming
329    Wyoming
Name: state, Length: 330, dtype: object

## Standardize the magnitude of numeric features

**<font color='teal'> Using sklearn preprocessing standardize the scale of the features of the dataframe except the name of the resort which we done't need in the dataframe for modeling, so it can be droppped here as well. Also, we want to hold out our response variable(s) so we can have their true values available for model performance review. Let's set `AdultWeekend` to the y variable as our response for scaling and modeling. Later we will go back and consider the `AdultWeekday`, `dayOpenLastYear`, and `projectedDaysOpen`. For now leave them in the development dataframe. </font>**

In [90]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df2.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df2.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

## Split into training and testing datasets

**<font color='teal'> Using sklearn model selection import train_test_split, and create a 75/25 split with the y = `AdultWeekend`. We will start by using the adult weekend ticket price as our response variable for modeling.</font>**

In [91]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

Here we start the actual modeling work. First let's fit a multiple linear regression model to predict the `AdultWeekend` price.

# Guided Capstone Step 5. Modeling

This is the fifth step in the Data Science Method. In the previous steps you cleaned and prepared the datasets. Now it's time to get into the most exciting part: modeling! In this exercise, you'll build three different models and compare each model's performance. In the end, you'll choose the best model for demonstrating insights to Big Mountain management.



### **The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.   **Modeling**
  * Fit Models with Training Data Set
  * Review Model Outcomes â€” Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

## Fit Models with a Training Dataset

**<font color='teal'> Using sklearn, fit the model on your training dataset.</font>**

#### Model 1

In [92]:
#all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

**<font color='teal'> Predict on the testing dataset and score the model performance with the y_test set and the y-pred values. The explained variance is a measure of the variation explained by the model. This is also known as the R-squared value. </font>**

Hint: you will have to use the `predict()` method here as it's used in this [DSM article](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-modeling-56b4233cad1b) about modeling.

In [93]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = model.predict(X_test)

## Review Model Outcomes â€” Iterate over additional models as needed

In [0]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# To do so, you will need to import them from sklearn.metrics. 
# You can plug y_test and y_pred into the functions to evaluate the model

**<font color='teal'> Print the intercept value from the linear model. </font>**

Hint: our linear regression model `lm` has an attribute `intercept_` for the intercept

In [94]:
lm.intercept_

64.10850171635681

**<font color='teal'> The intercept is the mean `AdultWeekend` price for all the resorts given the other characteristics. The addition or subtraction of each of the coefficient values in the regression are numeric adjustments applied to the intercept to provide a particular observation's value for the resulting `AdultWeekend` value. Also, because we took the time to scale our x values in the training data, we can compare each of the coeeficients for the features to determine the feature importances. Print the coefficient values from the linear model and sort in descending order to identify the top ten most important features.</font>** 


Hint: make sure to review the absolute value of the coefficients, because the adjustment may be positive or negative, but what we are looking for is the magnitude of impact on our response variable.

In [95]:
# You might want to make a pandas DataFrame displaying the coefficients for each state like so: 
df_model = pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'],)

In [96]:
df_model.sort_values(by='Coefficient',ascending=False)

                    Coefficient
New York           2.770298e+13
Michigan           2.614409e+13
Colorado           2.303446e+13
California         2.254136e+13
Pennsylvania       2.151039e+13
New Hampshire      1.983426e+13
Wisconsin          1.983426e+13
Vermont            1.923500e+13
Minnesota          1.861225e+13
Utah               1.796357e+13
Idaho              1.728604e+13
Montana            1.728604e+13
Massachusetts      1.657612e+13
Washington         1.582947e+13
Oregon             1.582947e+13
Maine              1.504060e+13
New Mexico         1.504060e+13
Wyoming            1.420248e+13
North Carolina     1.233785e+13
Connecticut        1.128023e+13
Ohio               1.128023e+13
West Virginia      1.010485e+13
Virginia           1.010485e+13
Illinois           1.010485e+13
Nevada             1.010485e+13
total_chairs       9.192768e+12
Alaska             8.764472e+12
Iowa               8.764472e+12
New Jersey         7.167095e+12
Missouri           7.167095e+12
Arizona            7.167095e+12
Indiana            7.167095e+12
South Dakota       7.167095e+12
Tennessee          5.075621e+12
Maryland           5.075621e+12
Rhode Island       5.075621e+12
fastQuads          3.484999e+12
surface            3.265183e+12
double             2.877400e+12
triple             2.566838e+12
quad               2.080328e+12
fastSixes          1.033130e+12
trams              8.876938e+11
fastEight          8.726899e+10
AdultWeekday       1.934717e+01
summit_elev        1.722000e+00
Runs               1.295685e+00
vertical_drop      1.124664e+00
NightSkiing_ac     8.005371e-01
clusters           7.145996e-01
daysOpenLastYear   5.244446e-01
LongestRun_mi      4.035645e-01
yearsOpen          3.549805e-01
Snow Making_ac     3.256531e-01
averageSnowfall    1.548462e-01
SkiableTerrain_ac  1.409302e-01
projectedDaysOpen  1.126709e-01
TerrainParks       9.390259e-02

**<font color='teal'>You should see that the top ten important features are different states. However, the state is not something the managers at the Big Mountain Resort can do anything about. Given that we care more about actionable traits associated with ticket pricing, rebuild the model without the state features and compare the results. </font>**

Hint: Try to construct another model using exactly the steps we followed above.

#### Model 2

In [97]:
dfns = df2.drop(dummy,axis=1)

In [98]:
dfns

,Name,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Alyeska Resort,3939,2500,1,0.0,0,2,2,0,0,2,7,76.0,2.000000,1.0,1610.0,113.000000,150.000000,60.0,669.000000,65.000000,85.00000,150.000000,550.0,0
1,Eaglecrest Ski Area,2600,1540,0,0.0,0,0,0,0,4,0,4,36.0,1.000000,2.0,640.0,60.000000,45.000000,44.0,350.000000,47.000000,53.00000,90.000000,0.0,0
2,Hilltop Ski Area,2090,294,0,0.0,0,0,0,1,0,2,3,13.0,1.000000,1.0,30.0,30.000000,150.000000,36.0,69.000000,30.000000,34.00000,152.000000,30.0,0
3,Arizona Snowbowl,11500,2300,0,0.0,1,0,2,2,1,2,8,55.0,4.000000,2.0,777.0,104.000000,122.000000,81.0,260.000000,89.000000,89.00000,122.000000,0.0,1
4,Sunrise Park Resort,11100,1800,0,0.0,0,1,2,3,1,0,7,65.0,2.000000,1.2,800.0,80.000000,115.000000,49.0,250.000000,74.000000,78.00000,104.000000,80.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Meadowlark Ski Lodge,9500,1000,0,0.0,0,0,0,1,1,1,3,14.0,1.000000,1.5,300.0,174.873239,115.103943,9.0,185.316456,57.916957,64.16681,120.053004,0.0,1
326,Sleeping Giant Ski Resort,7428,810,0,0.0,0,0,0,1,1,1,3,48.0,1.000000,1.0,184.0,18.000000,61.000000,81.0,310.000000,42.000000,42.00000,77.000000,0.0,1
327,Snow King Resort,7808,1571,0,0.0,0,0,1,1,1,0,3,32.0,2.000000,1.0,400.0,250.000000,121.000000,80.0,300.000000,59.000000,59.00000,123.000000,110.0,1
328,Snowy Range Ski & Recreation Area,9663,990,0,0.0,0,0,0,1,3,1,5,33.0,2.000000,0.7,75.0,30.000000,131.000000,59.0,250.000000,49.000000,49.00000,120.053004,0.0,1
329,White Pine Ski Area,9500,1100,0,0.0,0,0,0,2,0,0,2,25.0,2.820789,0.4,370.0,174.873239,115.103943,81.0,150.000000,57.916957,49.00000,120.053004,0.0,1

In [140]:
# first we import the preprocessing package from the sklearn library

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
Xns = dfns.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
yns = dfns.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scalerns = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaledns=scaler.transform(X)

In [135]:
X_scaledns

array([[-1.75024298e-01,  1.35728620e+00,  1.47965850e+00, ...,
         1.04347142e+00,  5.28388759e+00, -7.36407705e-01],
       [-5.34017876e-01,  3.42945226e-01, -3.08939686e-01, ...,
        -1.04716512e+00, -6.09611897e-01, -7.36407705e-01],
       [-6.70751800e-01, -9.73584832e-01, -3.08939686e-01, ...,
         1.11315930e+00, -2.88148289e-01, -7.36407705e-01],
       ...,
       [ 8.62276787e-01,  3.75699987e-01, -3.08939686e-01, ...,
         1.02684975e-01,  5.69088000e-01,  1.32303757e+00],
       [ 1.35961292e+00, -2.38187625e-01, -3.08939686e-01, ...,
        -9.90324405e-16, -6.09611897e-01,  1.32303757e+00],
       [ 1.31591169e+00, -1.21961055e-01, -3.08939686e-01, ...,
        -9.90324405e-16, -6.09611897e-01,  1.32303757e+00]])

In [137]:

lmns = linear_model.LinearRegression()
modelns = lm.fit(X_train,y_train)

In [138]:
y_predns = modelns.predict(X_test)

In [139]:
y_predns

array([ 57.71787672,  90.28037672,  78.95225172,  76.12412672,
        69.00693922,  77.20615797,  44.61631422,  46.99131422,
        94.03818922,  84.74912672,  50.60068922,  78.97568922,
        50.60850172,  71.02256422,  62.54600172,  92.89756422,
        41.97568922,  73.21787672,  62.69443922,  40.90537672,
       113.51475172,  36.80381422,  53.58506422,  49.32725172,
        48.03818922,  61.17881422,  76.38193922,  68.97178297,
        64.02256422,  66.36631422,  34.76084547,  58.76475172,
        80.56162672,  56.88193922,  75.60850172,  49.47568922,
        22.93662672,  28.94443922,  61.56162672,  37.15537672,
        48.46787672,  62.72568922,  86.83506422,  72.50693922,
        72.65537672,  58.70225172,  61.21787672, 165.76475172,
        37.70225172,  61.24131422,  68.45225172,  59.63975172,
        53.41318922,  44.23350172,  59.46787672,  42.01865797,
        85.71787672,  39.45225172, 119.51475172, 119.63975172,
        56.09287672,  53.37412672,  41.65537672,  80.96787672,
        64.45225172,  43.26475172,  36.44834547,  96.85068922,
        61.24912672,  24.56943922,  68.38193922, 146.38193922,
        57.84287672,  62.52256422,  75.17100172,  71.09678297,
        76.59287672,  58.62412672,  85.01475172,  71.91318922,
        52.48350172,  57.10850172,  43.16318922])

In [144]:
lmns.fit(Xns,yns)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [145]:
lmns.intercept_

12.642937433622755

In [146]:
df_modelns = pd.DataFrame(abs(lmns.coef_), Xns.columns, columns=['Coefficient'],)

In [147]:
df_modelns

                   Coefficient
summit_elev           0.001100
vertical_drop         0.001306
trams                 0.665364
fastEight             0.804856
fastSixes             0.285858
fastQuads             0.522566
quad                  0.750751
triple                0.606486
double                0.087465
surface               0.612485
total_chairs          0.170422
Runs                  0.027395
TerrainParks          0.054516
LongestRun_mi         0.295256
SkiableTerrain_ac     0.000247
Snow Making_ac        0.000575
daysOpenLastYear      0.030326
yearsOpen             0.002430
averageSnowfall       0.004966
AdultWeekday          0.835971
projectedDaysOpen     0.024137
NightSkiing_ac        0.010095
clusters             12.492478

**<font color='teal'> When reviewing our new model coefficients, we see `summit_elev` is now in the number two spot. This is also difficult to change from a management prespective and highly correlated with `base_elev` and `vertical_drop`.  This time, rebuild the model without the state features and without the `summit_elev` and without `base_elev`and compare the results. </font>**

#### Model 3

In [149]:
dflast = dfns.drop('summit_elev',axis=1)

In [150]:
dflast.head()

,Name,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Alyeska Resort,2500,1,0.0,0,2,2,0,0,2,7,76.0,2.0,1.0,1610.0,113.0,150.0,60.0,669.0,65.0,85.0,150.0,550.0,0
1,Eaglecrest Ski Area,1540,0,0.0,0,0,0,0,4,0,4,36.0,1.0,2.0,640.0,60.0,45.0,44.0,350.0,47.0,53.0,90.0,0.0,0
2,Hilltop Ski Area,294,0,0.0,0,0,0,1,0,2,3,13.0,1.0,1.0,30.0,30.0,150.0,36.0,69.0,30.0,34.0,152.0,30.0,0
3,Arizona Snowbowl,2300,0,0.0,1,0,2,2,1,2,8,55.0,4.0,2.0,777.0,104.0,122.0,81.0,260.0,89.0,89.0,122.0,0.0,1
4,Sunrise Park Resort,1800,0,0.0,0,1,2,3,1,0,7,65.0,2.0,1.2,800.0,80.0,115.0,49.0,250.0,74.0,78.0,104.0,80.0,1

In [151]:
X3 = dflast.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y3 = dflast.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler3 = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled3=scaler.transform(X)

In [152]:
lm3 = linear_model.LinearRegression()
model3 = lm3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)

In [154]:
lm3.fit(X3,y3)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [155]:
df_model3 = pd.DataFrame(abs(lm3.coef_), X3.columns, columns=['Coefficient'],)

In [156]:
df_model3

                   Coefficient
vertical_drop         0.002171
trams                 0.790826
fastEight             2.860040
fastSixes             0.712998
fastQuads             0.720273
quad                  1.099068
triple                0.904840
double                0.369540
surface               0.284404
total_chairs          0.128551
Runs                  0.014357
TerrainParks          0.023485
LongestRun_mi         0.271889
SkiableTerrain_ac     0.000085
Snow Making_ac        0.000263
daysOpenLastYear      0.044520
yearsOpen             0.002093
averageSnowfall       0.003970
AdultWeekday          0.841358
projectedDaysOpen     0.033550
NightSkiing_ac        0.007129
clusters              6.206776

## Identify the Final Model

**<font color='teal'> Review the model performances in the table below and choose the best model for proving insights to Big Mountain management about what features are driving ski resort lift ticket prices. Type your choice in the final markdown cell â€” you will discuss this selection more in the next step of the guided casptone. </font>**

| Model | Explained Variance| Mean Absolute Error|Features Dropped|
| --- | --- | --- | --- |
| Model 1. | 0. |  |-|
| Model 2. | 0.| |'state'|
| Model 3. | 0. | |'state','summit_elev','base_elev'|

Model Selection:

In [157]:
Model 3

SyntaxError: invalid syntax (<ipython-input-157-c9f7dec589e1>, line 1)